[package]
name = "hero_sol"
version = "0.0.1"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework", rev = "devnet" }
ctf = { local = "../challenges/movectf-6" }

[addresses]
hero_sol = "0x0"
sui = "0x2"
